# Generated by Django 3.1.7 on 2021-04-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0003_electronics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Electronics',
            new_name='Electronic',
        ),
    ]
