# Generated by Django 3.1.7 on 2021-04-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_login',
            name='status',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='tbl_registration',
            name='status',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
